export default [
    {
        path:'/my',
        name:"我的麦",
        component:()=>import("../../views/my.vue")
    },
    {
        path:'/login',
        name:"登陆麦账号",
        component:()=>import("../../components/my/login.vue")
    },
    {
        path:'/register',
        name:"注册麦账号",
        component:()=>import("../../components/my/register.vue")
    },
    {
        path:'/member',
        name:"会员",
        component:()=>import("../../components/my/member.vue")
    },
    {
        path:'/favourable',
        name:"我的优惠",
        component:()=>import("../../components/my/favourable.vue")
    },
    {
        path:'/service',
        name:"服务中心",
        component:()=>import("../../components/my/service.vue")
    },
    {
        path:'/search',
        name:"搜索",
        component:()=>import("../../views/search.vue")
    },
    {
        path:'/myF',
        name:"我的F码",
        component:()=>import("../../components/my/myF.vue")
    },
    {
        path:'/gift',
        name:"礼物",
        component:()=>import("../../components/my/gift.vue")
    },
    {
        path:'/set',
        name:"设置",
        component:()=>import("../../components/my/set.vue")
    },
]